"""cria tabela prefeituras

Revision ID: 7d93056eb539
Revises: 951d6782d804
Create Date: 2026-07-04 01:01:17.445234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d93056eb539'
down_revision: Union[str, None] = '951d6782d804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prefeituras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('site_oficial', sa.String(length=255), nullable=True),
    sa.Column('diario_oficial', sa.String(length=255), nullable=True),
    sa.Column('portal_licitacao', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ultima_verificacao', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipio_id')
    )
    op.create_index(op.f('ix_prefeituras_id'), 'prefeituras', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prefeituras_id'), table_name='prefeituras')
    op.drop_table('prefeituras')
    # ### end Alembic commands ###
