"""criar tabela municipios

Revision ID: 951d6782d804
Revises: 
Create Date: 2026-07-03 21:27:36.536017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '951d6782d804'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_ibge', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_ibge')
    )
    op.create_index(op.f('ix_municipios_id'), 'municipios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_municipios_id'), table_name='municipios')
    op.drop_table('municipios')
    # ### end Alembic commands ###
