"""adiciona observacao em prefeituras

Revision ID: a0baf3a03a14
Revises: 7d93056eb539
Create Date: 2026-07-04 01:22:09.899211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0baf3a03a14'
down_revision: Union[str, None] = '7d93056eb539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prefeituras', sa.Column('observacao', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prefeituras', 'observacao')
    # ### end Alembic commands ###
